In [3]:
import pandas as pd

In [4]:
data=pd.read_csv('preprocessed_train_data.csv')

In [5]:
data

PID                                          Text data  \
0         train_pid_1  waiting mind breakdown new year feeling isnt a...   
1         train_pid_2  new years resolution im gon na get ass therapi...   
2         train_pid_3  new year somone else feeling like 2020 last ye...   
3         train_pid_4  story guess hi im germany english mostly self ...   
4         train_pid_5     sat dark cried going new year great start 2020   
...               ...                                                ...   
11029  train_pid_5033      never want rely anyone lowkey always probably   
11030  train_pid_5051  anyone else feel like every single week dumb s...   
11031  train_pid_1722  well well im done cant believe im saying ive f...   
11032  train_pid_5373  thinking maxing two credit cards buy gaming la...   
11033  train_pid_5796  ive taking consistent showers last 2 weeks im ...   

                Label  
0            moderate  
1            moderate  
2            moderate  
3            moderate  
4            moderate  
...               ...  
11029  not depression  
11030  not depression  
11031  not depression  
11032  not depression  
11033  not depression  

[11034 rows x 3 columns]

In [6]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
x = data['Text data']
y = data['Label']
x = np.array(data.iloc[:,0].values)
y = np.array(data['Label'].values)
w2v = TfidfVectorizer()
x = w2v.fit_transform(data['Text data']).toarray()

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0, shuffle = True)

In [10]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [11]:
x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
y_train

array(['severe', 'severe', 'severe', ..., 'not depression',
       'not depression', 'moderate'], dtype=object)

In [13]:
y_test

array(['moderate', 'moderate', 'not depression', ..., 'not depression',
       'not depression', 'severe'], dtype=object)

In [14]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB,MultinomialNB

In [15]:
lr = LogisticRegression()
oneVsRestlr = OneVsRestClassifier(lr)
oneVsRestlr.fit(x_train, y_train)
y_pred = oneVsRestlr.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Logistic Regression: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Logistic Regression: % 73.24
Confusion Matrix
[[ 603  317  138]
 [ 254  819   64]
 [  77   36 1003]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.65      0.57      0.61      1058
not depression       0.70      0.72      0.71      1137
        severe       0.83      0.90      0.86      1116

      accuracy                           0.73      3311
     macro avg       0.73      0.73      0.73      3311
  weighted avg       0.73      0.73      0.73      3311

Precision : 0.732407127755965
Recall : 0.732407127755965
F1-score : 0.732407127755965


In [16]:
gnb = GaussianNB()
oneVsRestgnb = OneVsRestClassifier(gnb)
oneVsRestgnb.fit(x_train, y_train)
y_pred = oneVsRestgnb.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Gaussian Naive Bayes: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Gaussian Naive Bayes: % 60.86
Confusion Matrix
[[ 384  132  542]
 [ 121  529  487]
 [  10    4 1102]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.75      0.36      0.49      1058
not depression       0.80      0.47      0.59      1137
        severe       0.52      0.99      0.68      1116

      accuracy                           0.61      3311
     macro avg       0.69      0.61      0.58      3311
  weighted avg       0.69      0.61      0.59      3311

Precision : 0.6085774690425854
Recall : 0.6085774690425854
F1-score : 0.6085774690425854


In [17]:
rf = RandomForestClassifier(n_estimators=100 ,criterion='entropy' , random_state=0)
oneVsRestrf = OneVsRestClassifier(rf)
oneVsRestrf.fit(x_train, y_train)
y_pred = oneVsRestrf.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Random Forest: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Random Forest: % 84.23
Confusion Matrix
[[ 795  239   24]
 [ 223  904   10]
 [  22    4 1090]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.76      0.75      0.76      1058
not depression       0.79      0.80      0.79      1137
        severe       0.97      0.98      0.97      1116

      accuracy                           0.84      3311
     macro avg       0.84      0.84      0.84      3311
  weighted avg       0.84      0.84      0.84      3311

Precision : 0.8423437028088191
Recall : 0.8423437028088191
F1-score : 0.8423437028088191


In [18]:
mnb = MultinomialNB(alpha=1.0,fit_prior=True)
oneVsRestmnb = OneVsRestClassifier(mnb)
oneVsRestmnb.fit(x_train, y_train)
y_pred = oneVsRestmnb.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Multinomial Naive Bayes: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Multinomial Naive Bayes: % 64.94
Confusion Matrix
[[ 704   85  269]
 [ 500  429  208]
 [  91    8 1017]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.54      0.67      0.60      1058
not depression       0.82      0.38      0.52      1137
        severe       0.68      0.91      0.78      1116

      accuracy                           0.65      3311
     macro avg       0.68      0.65      0.63      3311
  weighted avg       0.69      0.65      0.63      3311

Precision : 0.6493506493506493
Recall : 0.6493506493506493
F1-score : 0.6493506493506493


In [20]:
dt = DecisionTreeClassifier()
oneVsRestdt = OneVsRestClassifier(dt)
oneVsRestdt.fit(x_train, y_train)
y_pred = oneVsRestdt.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Decision Tree: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Decision Tree: % 71.16
Confusion Matrix
[[ 348  305  405]
 [  94  908  135]
 [  13    3 1100]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.76      0.33      0.46      1058
not depression       0.75      0.80      0.77      1137
        severe       0.67      0.99      0.80      1116

      accuracy                           0.71      3311
     macro avg       0.73      0.70      0.68      3311
  weighted avg       0.73      0.71      0.68      3311

Precision : 0.7115675022651767
Recall : 0.7115675022651767
F1-score : 0.7115675022651767


In [ ]:
knn = KNeighborsClassifier(n_neighbors=10 , metric= 'minkowski' , p = 4)
oneVsRestknn = OneVsRestClassifier(knn)
oneVsRestknn.fit(x_train, y_train)
y_pred = oneVsRestknn.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic K Nearest Neighbor: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

In [ ]:
data=pd.read_csv('preprocessed_dev_data.csv')

In [ ]:
data

In [ ]:
x = data['text data']
y = data['Class labels']
x = np.array(data.iloc[:,0].values)
y = np.array(data['Class labels'].values)
w2v = TfidfVectorizer()
x = w2v.fit_transform(data['Text data']).toarray()

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0, shuffle = True)

In [16]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
y_train

array([1, 1, 1, ..., 2, 2, 0], dtype=int64)

In [19]:
y_test

array([0, 0, 2, ..., 2, 2, 1], dtype=int64)

In [21]:
oneVsRestlr.fit(x_train, y_train)
y_pred = oneVsRestlr.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Logistic Regression: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Logistic Regression: % 73.24
Confusion Matrix
[[ 603  138  317]
 [  77 1003   36]
 [ 254   64  819]]
Classification Report
              precision    recall  f1-score   support

           0       0.65      0.57      0.61      1058
           1       0.83      0.90      0.86      1116
           2       0.70      0.72      0.71      1137

    accuracy                           0.73      3311
   macro avg       0.73      0.73      0.73      3311
weighted avg       0.73      0.73      0.73      3311

Precision : 0.732407127755965
Recall : 0.732407127755965
F1-score : 0.732407127755965


In [22]:
oneVsRestgnb.fit(x_train, y_train)
y_pred = oneVsRestgnb.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Gaussian Naive Bayes: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Gaussian Naive Bayes: % 70.28
Confusion Matrix
[[384 122 552]
 [ 10 966 140]
 [121  39 977]]
Classification Report
              precision    recall  f1-score   support

           0       0.75      0.36      0.49      1058
           1       0.86      0.87      0.86      1116
           2       0.59      0.86      0.70      1137

    accuracy                           0.70      3311
   macro avg       0.73      0.70      0.68      3311
weighted avg       0.73      0.70      0.69      3311

Precision : 0.7028088190878888
Recall : 0.7028088190878888
F1-score : 0.7028088190878888


In [23]:
oneVsRestrf.fit(x_train, y_train)
y_pred = oneVsRestrf.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Random Forest: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Random Forest: % 84.23
Confusion Matrix
[[ 795   24  239]
 [  22 1090    4]
 [ 223   10  904]]
Classification Report
              precision    recall  f1-score   support

           0       0.76      0.75      0.76      1058
           1       0.97      0.98      0.97      1116
           2       0.79      0.80      0.79      1137

    accuracy                           0.84      3311
   macro avg       0.84      0.84      0.84      3311
weighted avg       0.84      0.84      0.84      3311

Precision : 0.8423437028088191
Recall : 0.8423437028088191
F1-score : 0.8423437028088191


In [24]:
oneVsRestmnb.fit(x_train, y_train)
y_pred = oneVsRestmnb.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Multinomial Naive Bayes: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Multinomial Naive Bayes: % 64.94
Confusion Matrix
[[ 704  269   85]
 [  91 1017    8]
 [ 500  208  429]]
Classification Report
              precision    recall  f1-score   support

           0       0.54      0.67      0.60      1058
           1       0.68      0.91      0.78      1116
           2       0.82      0.38      0.52      1137

    accuracy                           0.65      3311
   macro avg       0.68      0.65      0.63      3311
weighted avg       0.69      0.65      0.63      3311

Precision : 0.6493506493506493
Recall : 0.6493506493506493
F1-score : 0.6493506493506493


In [ ]:
oneVsRestdt.fit(x_train, y_train)
y_pred = oneVsRestdt.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Decision Tree: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

In [ ]:
oneVsRestknn.fit(x_train, y_train)
y_pred = oneVsRestknn.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic K Nearest Neighbor: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')