In [1]:
import pandas as pd

In [5]:
data=pd.read_csv('preprocessed_train_data.csv')

In [6]:
data

Pid                                          text data  \
0        dev_pid_1  im scared lie every day say ill make think mig...   
1        dev_pid_2  new wanted vent finally realized im kind bad m...   
2        dev_pid_3  im sad kinda always issue wouldnt say bad peer...   
3        dev_pid_4  lonely alone immediately family members dead d...   
4        dev_pid_5  year trash dont know im posting dont even know...   
...            ...                                                ...   
6502  dev_pid_2514  anyone feared theyll kill loved ones sleep uni...   
6503  dev_pid_2829  finally got fulltime job feel even worse maybe...   
6504  dev_pid_2260  deal boredomnothing satisfying anymore days ta...   
6505  dev_pid_2653                   got bed showered morning removed   
6506  dev_pid_2460  depressed suicidal 2018 start 2020 ive woken d...   

        Class labels  
0           moderate  
1           moderate  
2           moderate  
3           moderate  
4           moderate  
...              ...  
6502  not depression  
6503  not depression  
6504  not depression  
6505  not depression  
6506  not depression  

[6507 rows x 3 columns]

In [8]:
data.head()

Pid                                          text data Class labels
0  dev_pid_1  im scared lie every day say ill make think mig...     moderate
1  dev_pid_2  new wanted vent finally realized im kind bad m...     moderate
2  dev_pid_3  im sad kinda always issue wouldnt say bad peer...     moderate
3  dev_pid_4  lonely alone immediately family members dead d...     moderate
4  dev_pid_5  year trash dont know im posting dont even know...     moderate

In [10]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
x = data['Text data']
y = data['Label']
x = np.array(data.iloc[:,0].values)
y = np.array(data['Label'].values)
cv = CountVectorizer()
x = cv.fit_transform(data['Text data']).toarray()

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0, shuffle = True)

In [12]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
y_train

array(['not depression', 'severe', 'moderate', ..., 'moderate', 'severe',
       'severe'], dtype=object)

In [15]:
y_test

array(['moderate', 'severe', 'moderate', ..., 'severe', 'not depression',
       'not depression'], dtype=object)

In [16]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [17]:
mdl = LogisticRegression()
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Logistic Regression: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

C:\Users\VASANTHARAN 21ADR056\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\VASANTHARAN 21ADR056\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html

Test Accuracy Score of Basic Logistic Regression: % 86.33
Confusion Matrix
[[426 175  42]
 [ 48 595   2]
 [  0   0 665]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.90      0.66      0.76       643
not depression       0.77      0.92      0.84       645
        severe       0.94      1.00      0.97       665

      accuracy                           0.86      1953
     macro avg       0.87      0.86      0.86      1953
  weighted avg       0.87      0.86      0.86      1953

Precision : 0.8632872503840245
Recall : 0.8632872503840245
F1-score : 0.8632872503840245


In [18]:
mdl = GaussianNB()
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Gaussian Naive Bayes: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Gaussian Naive Bayes: % 72.3
Confusion Matrix
[[272 133 238]
 [ 44 475 126]
 [  0   0 665]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.86      0.42      0.57       643
not depression       0.78      0.74      0.76       645
        severe       0.65      1.00      0.79       665

      accuracy                           0.72      1953
     macro avg       0.76      0.72      0.70      1953
  weighted avg       0.76      0.72      0.70      1953

Precision : 0.7229902713773682
Recall : 0.7229902713773682
F1-score : 0.722990271377368


In [ ]:
mdl = RandomForestClassifier(n_estimators=100 ,criterion='entropy' , random_state=0)
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Random Forest: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

In [20]:
mdl = MultinomialNB(alpha=1.0,fit_prior=True)
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Multinomial Naive Bayes: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Multinomial Naive Bayes: % 81.82
Confusion Matrix
[[467 103  73]
 [138 486  21]
 [ 12   8 645]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.76      0.73      0.74       643
not depression       0.81      0.75      0.78       645
        severe       0.87      0.97      0.92       665

      accuracy                           0.82      1953
     macro avg       0.81      0.82      0.81      1953
  weighted avg       0.82      0.82      0.82      1953

Precision : 0.8182283666154634
Recall : 0.8182283666154634
F1-score : 0.8182283666154634


In [ ]:
mdl = SVC()
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Support Vector Classifer: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

In [ ]:
mdl = DecisionTreeClassifier()
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Decision Tree: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

In [ ]:
mdl = KNeighborsClassifier(n_neighbors=10 , metric= 'minkowski' , p = 4)
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic K Nearest Neighbor: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

In [5]:
data=pd.read_csv('preprocessed_dev_data.csv')

In [6]:
data

Pid                                          text data  \
0        dev_pid_1  im scared lie every day say ill make think mig...   
1        dev_pid_2  new wanted vent finally realized im kind bad m...   
2        dev_pid_3  im sad kinda always issue wouldnt say bad peer...   
3        dev_pid_4  lonely alone immediately family members dead d...   
4        dev_pid_5  year trash dont know im posting dont even know...   
...            ...                                                ...   
6502  dev_pid_2514  anyone feared theyll kill loved ones sleep uni...   
6503  dev_pid_2829  finally got fulltime job feel even worse maybe...   
6504  dev_pid_2260  deal boredomnothing satisfying anymore days ta...   
6505  dev_pid_2653                   got bed showered morning removed   
6506  dev_pid_2460  depressed suicidal 2018 start 2020 ive woken d...   

        Class labels  
0           moderate  
1           moderate  
2           moderate  
3           moderate  
4           moderate  
...              ...  
6502  not depression  
6503  not depression  
6504  not depression  
6505  not depression  
6506  not depression  

[6507 rows x 3 columns]

In [8]:
data.head()

Pid                                          text data Class labels
0  dev_pid_1  im scared lie every day say ill make think mig...     moderate
1  dev_pid_2  new wanted vent finally realized im kind bad m...     moderate
2  dev_pid_3  im sad kinda always issue wouldnt say bad peer...     moderate
3  dev_pid_4  lonely alone immediately family members dead d...     moderate
4  dev_pid_5  year trash dont know im posting dont even know...     moderate

In [10]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
x = data['text data']
y = data['Class labels']
x = np.array(data.iloc[:,0].values)
y = np.array(data['Class labels'].values)
cv = CountVectorizer()
x = cv.fit_transform(data['text data']).toarray()

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 0, shuffle = True)

In [12]:
x_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
x_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
y_train

array(['not depression', 'severe', 'moderate', ..., 'moderate', 'severe',
       'severe'], dtype=object)

In [15]:
y_test

array(['moderate', 'severe', 'moderate', ..., 'severe', 'not depression',
       'not depression'], dtype=object)

In [16]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [17]:
mdl = LogisticRegression()
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Logistic Regression: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

C:\Users\VASANTHARAN 21ADR056\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\VASANTHARAN 21ADR056\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html

Test Accuracy Score of Basic Logistic Regression: % 86.33
Confusion Matrix
[[426 175  42]
 [ 48 595   2]
 [  0   0 665]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.90      0.66      0.76       643
not depression       0.77      0.92      0.84       645
        severe       0.94      1.00      0.97       665

      accuracy                           0.86      1953
     macro avg       0.87      0.86      0.86      1953
  weighted avg       0.87      0.86      0.86      1953

Precision : 0.8632872503840245
Recall : 0.8632872503840245
F1-score : 0.8632872503840245


In [18]:
mdl = GaussianNB()
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Gaussian Naive Bayes: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Gaussian Naive Bayes: % 72.3
Confusion Matrix
[[272 133 238]
 [ 44 475 126]
 [  0   0 665]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.86      0.42      0.57       643
not depression       0.78      0.74      0.76       645
        severe       0.65      1.00      0.79       665

      accuracy                           0.72      1953
     macro avg       0.76      0.72      0.70      1953
  weighted avg       0.76      0.72      0.70      1953

Precision : 0.7229902713773682
Recall : 0.7229902713773682
F1-score : 0.722990271377368


In [22]:
mdl = RandomForestClassifier(n_estimators=100 ,criterion='entropy' , random_state=0)
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Random Forest: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Random Forest: % 92.99
Confusion Matrix
[[577  64   2]
 [ 71 574   0]
 [  0   0 665]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.89      0.90      0.89       643
not depression       0.90      0.89      0.89       645
        severe       1.00      1.00      1.00       665

      accuracy                           0.93      1953
     macro avg       0.93      0.93      0.93      1953
  weighted avg       0.93      0.93      0.93      1953

Precision : 0.9298515104966718
Recall : 0.9298515104966718
F1-score : 0.9298515104966718


In [20]:
mdl = MultinomialNB(alpha=1.0,fit_prior=True)
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Multinomial Naive Bayes: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

Test Accuracy Score of Basic Multinomial Naive Bayes: % 81.82
Confusion Matrix
[[467 103  73]
 [138 486  21]
 [ 12   8 645]]
Classification Report
                precision    recall  f1-score   support

      moderate       0.76      0.73      0.74       643
not depression       0.81      0.75      0.78       645
        severe       0.87      0.97      0.92       665

      accuracy                           0.82      1953
     macro avg       0.81      0.82      0.81      1953
  weighted avg       0.82      0.82      0.82      1953

Precision : 0.8182283666154634
Recall : 0.8182283666154634
F1-score : 0.8182283666154634


In [23]:
mdl = SVC()
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Support Vector Classifer: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

KeyboardInterrupt: 

In [ ]:
mdl = DecisionTreeClassifier()
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic Decision Tree: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')

In [ ]:
mdl = KNeighborsClassifier(n_neighbors=10 , metric= 'minkowski' , p = 4)
oneVsRest = OneVsRestClassifier(mdl)
oneVsRest.fit(x_train, y_train)
y_pred = oneVsRest.predict(x_test)
accuracy = round(accuracy_score(y_test, y_pred) * 100, 2)
precision, recall, f1score, support = score(y_test, y_pred, average='micro')
print(f'Test Accuracy Score of Basic K Nearest Neighbor: % {accuracy}')
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix")
print(cm)
from sklearn.metrics import classification_report
print("Classification Report")
print(classification_report(y_test,y_pred))
print(f'Precision : {precision}')
print(f'Recall : {recall}')
print(f'F1-score : {f1score}')